### ISSUE TITLE
i got this error on import torch 

### ISSUE THREAD

**Issue by aliikram97** [marcusvlc/pytorch-on-rpi#2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by marcusvlc** [comment]
Hello @aliikram97, how are you?

Have you tried following the troubleshooting steps described in the README?

**Comment by aliikram97** [comment]
Yes i did actually
